---
use_default_settings: true

server:
  limiter: true
  image_proxy: true
  method: GET # https://github.com/searxng/searxng/pull/3619
  public_instance: false

search:
  safe_search: 0
  autocomplete: ""
  favicon_resolver: ""
  languages:
    - all
    - en
    - en-AU
  formats:
    - html
    - json
    - rss
  max_page: 0
  # ban time in seconds after engine errors
  ban_time_on_fail: 5
  # max ban time in seconds after engine errors
  max_ban_time_on_fail: 120
  suspended_times:
    # Engine suspension time after error (in seconds; set to 0 to disable)
    # For error "Access denied" and "HTTP error [402, 403]"
    SearxEngineAccessDenied: 86400
    # For error "CAPTCHA"
    SearxEngineCaptcha: 86400
    # For error "Too many request" and "HTTP error 429"
    SearxEngineTooManyRequests: 3600
    # Cloudflare CAPTCHA
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    # ReCAPTCHA
    recaptcha_SearxEngineCaptcha: 604800

general:
  instance_name: Strallow Search
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

ui:
  default_theme: simple
  infinite_scroll: true
  query_in_title: true
  results_on_new_tab: true
  static_use_hash: true
  theme_args:
    simple_style: auto

categories_as_tabs:
  general:
  images:
  videos:
  map:

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true
  searx.plugins.tor_check.SXNGPlugin:
    active: false

hostnames:
  replace:
    '(.*\\.)?youtube\\.com$': "youtube.${SECRET_DOMAIN}"
    '(.*\\.)?reddit\\.com$': "reddit.${SECRET_DOMAIN}"
    '(.*\\.)?medium\\.com$': "medium.${SECRET_DOMAIN}"
    '(.*\\.)?twitter\\.com$': "twitter.${SECRET_DOMAIN}"
  high_priority:
    - (.*)\/blog\/(.*)
    - (.*\.)?wikipedia.org$
    - (.*\.)?github.com$
    - (.*\.)?reddit.com$
    - (.*\.)?docker.com$
    - (.*\.)?archlinux.org$
    - (.*\.)?stackoverflow.com$
    - (.*\.)?askubuntu.com$
    - (.*\.)?superuser.com$

engines:
  - name: braveapi
    engine: braveapi
    api_key: "${BRAVE_API_KEY}"
    results_per_page: 20
    inactive: false
    disabled: false
