---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KARAKEEP_API_KEY: "{{ .KARAKEEP_API_KEY }}"
  dataFrom:
    - extract:
        key: toolhive
