---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./helmrelease.yaml
  # - ./mcpgroup.yaml
  - ./mcptelemetryconfig.yaml
  - ./podmonitor.yaml
  - ./virtualmcpserver.yaml
  - ./httproute.yaml
  - ./embeddingserver.yaml
  - ./rbac.yaml
