---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: context7-mcp
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: context7-mcp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: context7
