---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glados
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: glados-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HERMES_API_SERVER_KEY: "{{ .HERMES_API_SERVER_KEY }}"
  dataFrom:
    - extract:
        key: hermes
