---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname toolhive
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: toolhive-crds
  path: ./kubernetes/apps/ai/toolhive/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname toolhive-crds
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./kubernetes/apps/ai/toolhive/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname toolhive-mcps
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: toolhive
  path: ./kubernetes/apps/ai/toolhive/mcps
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
