---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pinchflat
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pinchflat-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        youtube_cookies.txt: "{{ .youtube_cookies }}"
  dataFrom:
    - extract:
        key: youtube-cookies
