---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindsight
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hindsight-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HINDSIGHT_API_LLM_API_KEY: "{{ .HINDSIGHT_API_LLM_API_KEY }}"
        HINDSIGHT_API_LLM_BASE_URL: "{{ .HINDSIGHT_API_LLM_BASE_URL }}"
        ## DB
        HINDSIGHT_DB_USER: &dbUser "{{ .HINDSIGHT_DB_USER }}"
        HINDSIGHT_DB_PASSWORD: &dbPass "{{ .HINDSIGHT_DB_PASSWORD }}"
        HINDSIGHT_DB_NAME: &dbName "{{ .HINDSIGHT_DB_NAME }}"
        HINDSIGHT_API_DATABASE_URL: postgresql://${HINDSIGHT_DB_USER}:${HINDSIGHT_DB_PASSWORD}@postgres-vecto-rw.databases.svc.cluster.local:5432/${HINDSIGHT_DB_NAME}
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres-vecto-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: hindsight
    - extract:
        key: cloudnative-pg
