---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Immich
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: &dbHost postgres-vecto-rw.databases.svc.cluster.local
        DB_USERNAME: &dbUser "{{ .POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .POSTGRES_PASS }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        REDIS_HOSTNAME: immich-dragonfly-db.selfhosted.svc.cluster.local
        REDIS_PORT: "6379"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Config
        immich-config.yaml: |
          backup:
            database:
              enabled: false
          ffmpeg:
            crf: 23
            threads: 2
            preset: veryfast
            targetVideoCodec: hevc
            acceptedVideoCodecs: [h264, hevc]
            targetAudioCodec: aac
            acceptedAudioCodecs: [aac, mp3]
            targetResolution: "720"
            maxBitrate: "0"
            bframes: "-1"
            refs: 0
            gopSize: 0
            temporalAQ: false
            cqMode: auto
            twoPass: false
            preferredHwDevice: auto
            transcode: required
            accelDecode: true
            tonemap: hable
            accel: qsv
          job:
            backgroundTask:
              concurrency: 5
            smartSearch:
              concurrency: 2
            metadataExtraction:
              concurrency: 5
            faceDetection:
              concurrency: 2
            search:
              concurrency: 5
            sidecar:
              concurrency: 5
            library:
              concurrency: 5
            migration:
              concurrency: 5
            thumbnailGeneration:
              concurrency: 5
            videoConversion:
              concurrency: 1
            notifications:
              concurrency: 5
          logging:
            enabled: true
            level: debug
          machineLearning:
            enabled: true
            urls: [http://immich-machine-learning.selfhosted:3003]
            clip:
              enabled: true
              modelName: ViT-B-16-SigLIP__webli
            facialRecognition:
              enabled: true
              modelName: buffalo_l
              minScore: 0.7
              maxDistance: 0.5
              minFaces: 5
          map:
            enabled: true
          reverseGeocoding:
            enabled: true
          oauth:
            autoLaunch: true
            autoRegister: true
            buttonText: Login with Movishell
            clientId: "{{ .IMMICH_CLIENT_ID }}"
            clientSecret: "{{ .IMMICH_CLIENT_SECRET }}"
            defaultStorageQuota: 0
            enabled: true
            issuerUrl: https://id.${SECRET_DOMAIN}
            mobileOverrideEnabled: false
            mobileRedirectUri: ""
            scope: openid email profile
            signingAlgorithm: RS256
            storageLabelClaim: preferred_username
            storageQuotaClaim: immich_quota
          passwordLogin:
            enabled: false
          storageTemplate:
            enabled: true
            hashVerificationEnabled: true
            template: "{{`{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}`}}"
          image:
            thumbnail:
              format: webp
              size: 480
              quality: 80
            preview:
              format: jpeg
              size: 1440
              quality: 80
            colorspace: p3
            extractEmbedded: false
          newVersionCheck:
            enabled: false
          trash:
            enabled: true
            days: 7
          theme:
            customCss: ""
          library:
            scan:
              enabled: true
              cronExpression: "0 0 * * *"
            watch:
              enabled: false
          server:
            externalDomain: https://photos.${SECRET_DOMAIN}
            loginPageMessage: ""
          notifications:
            smtp:
              enabled: true
              from: "Photos <noreply@${SECRET_DOMAIN}>"
              replyTo: ""
              transport:
                ignoreCert: false
                host: "{{ .SMTP_SERVER }}"
                port: "{{ .SMTP_PORT }}"
                username: "{{ .SMTP_USERNAME }}"
                password: "{{ .SMTP_PASSWORD }}"
          user:
            deleteDelay: 2
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
    - extract:
        key: pocket-id
    - extract:
        key: smtp-relay
