---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actualsync
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actualsync-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACTUAL_SYNC_ID: "{{ .ACTUAL_SYNC_ID }}"
        ACTUAL_PASSWORD: "{{ .ACTUAL_PASSWORD }}"
        UP_USER_TOKEN: "{{ .UP_USER_TOKEN }}"
        UP_ACCOUNT_ID: "{{ .UP_ACCOUNT_ID }}"
        UP_ACCOUNT_ID2: "{{ .UP_ACCOUNT_ID2 }}"
        UP_ACCOUNT_ID3: "{{ .UP_ACCOUNT_ID3 }}"
        UP_ACCOUNT_ID4: "{{ .UP_ACCOUNT_ID4 }}"
  dataFrom:
    - extract:
        key: actualsync
