---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## API Keys
        LITELLM_API_KEY: "{{ .APIKEY_HERMES }}"
        ## Connections
        WHATSAPP_ALLOWED_USERS: "{{ .WHATSAPP_PHONE_NUMBER }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        ## Tools
        FIRECRAWL_API_KEY: "{{ .FIRECRAWL_API_KEY }}"
  dataFrom:
    - extract:
        key: hermes
    - extract:
        key: litellm
