---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## API Keys
        LITELLM_API_KEY: "{{ .APIKEY_HERMES }}"
        OPENCODE_GO_API_KEY: "{{ .OPENCODE_GO_API_KEY }}"
        ## Connections
        WHATSAPP_ALLOWED_USERS: "{{ .WHATSAPP_PHONE_NUMBER }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_HOME_CHANNEL: "{{ .DISCORD_HOME_CHANNEL }}"
        DISCORD_HOME_CHANNEL_NAME: "{{ .DISCORD_HOME_CHANNEL_NAME }}"
        ## Hermes
        API_SERVER_KEY: "{{ .HERMES_API_SERVER_KEY }}"
        ## Tools
        FIRECRAWL_API_KEY: "{{ .FIRECRAWL_API_KEY }}"
  dataFrom:
    - extract:
        key: hermes
    - extract:
        key: litellm
