---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bambuddy-mcp
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bambuddy-mcp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BAMBUDDY_API_KEY: "{{ .BAMBUDDY_API_KEY }}"
  dataFrom:
    - extract:
        key: bambuddy
