---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: bambuddy-mcp
spec:
  image: ghcr.io/astral-sh/uv:python3.12-alpine
  transport: stdio
  proxyMode: streamable-http
  groupRef:
    name: mcp-tools
  env:
    - name: BAMBUDDY_URL
      value: bambuddy.selfhosted.svc.cluster.local:8000
  secrets:
    - name: bambuddy-mcp-secret
      key: BAMBUDDY_API_KEY
      targetEnvName: BAMBUDDY_API_KEY
  args:
    - uvx
    - bambuddy-mcp@0.2.0
