---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencode
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opencode-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LITELLM_API_KEY: "{{ .LITELLM_API_KEY }}"
  dataFrom:
    - extract:
        key: opencode
